version: '3.8'

services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    volumes:
      - ./data/etc:/etc/bind
      - ./data/var:/var/cache/bind
    ports:
      - "53:53"
      - "53:53/udp"
    restart: unless-stopped

  cliente:
    image: alpine:latest
    container_name: client
    stdin_open: true
    tty: true
    depends_on:
      - bind9