version: '3'
services:
  asir_apache:
    image: httpd:latest
    container_name: asir_apache
    ports:
      - "90:80"
    volumes:
      - ./home/admin/apache/dns:/usr/local/apache2/conf:rw
    networks:
      asir_network:
        ipv4_address: 172.20.0.2

  asir_dns:
    image: ubuntu/bind9
    container_name: asir_dns
    platform: linux/amd64
    ports:
      - "53:53"
    networks:
      asir_network:
        ipv4_address: 172.20.0.3
  cliente:
    container_name: asir_cliente
    image: ubuntu:latest
    platform: linux/amd64
    tty: true
    stdin_open: true
    dns:
      -172.20.0.3
    networks:
      asir_network:
        ipv4_address: 172.20.0.5
networks:
  asir_network:
    external: true


